fragment FichesParts on Fiches {
  __typename
  _warning
  _warn2
  refID
  title
  createdAt
  updatedAt
  language
  published
  _metadatas
  refType
  versions {
    __typename
    version
    idRef
  }
  people
  responsible {
    __typename
    responsible {
      ... on Personas {
        __typename
        _warning
        title
        createdAt
        updatedAt
        language
        published
        shortName
        _corps_de_la_fiche
        body
      }
      ... on Document {
        _sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        id
      }
    }
  }
  lifecycle
  environmental_impact
  priority_implementation
  scope
  saved_resources
  _corps_de_la_fiche
  body
  validations {
    __typename
    rule
    maxValue
  }
}

fragment LexiqueParts on Lexique {
  __typename
  title
  createdAt
  updatedAt
  language
  published
  _corps_de_la_fiche
  body
}

fragment PersonasParts on Personas {
  __typename
  _warning
  title
  createdAt
  updatedAt
  language
  published
  shortName
  _corps_de_la_fiche
  body
}

fragment HomeParts on Home {
  __typename
  _warning
  title
  createdAt
  updatedAt
  language
  published
  _corps_de_la_fiche
  body
}

fragment MentionsLegalesParts on MentionsLegales {
  __typename
  _warning
  title
  createdAt
  updatedAt
  language
  published
  _corps_de_la_fiche
  body
}
