fragment FichesParts on Fiches {
  __typename
  _warning
  refID
  title
  createdAt
  updatedAt
  language
  published
  _metadatas
  people
  scope
  responsible
  lifecycle
  priority_implementation
  environmental_impact
  saved_resources
  _corps_de_la_fiche
  body
  validations {
    __typename
    rule
    maxValue
  }
}

fragment LexiqueParts on Lexique {
  __typename
  _warning
  title
  createdAt
  updatedAt
  language
  published
  _corps_de_la_fiche
  body
}

fragment PersonnasParts on Personnas {
  __typename
  _warning
  title
  createdAt
  updatedAt
  language
  published
  _corps_de_la_fiche
  body
}

fragment PagesParts on Pages {
  __typename
  _warning
  title
  createdAt
  updatedAt
  language
  published
  _corps_de_la_fiche
  useProse
  body
}

fragment SiteDataParts on SiteData {
  __typename
  _warning
  _seo
  title
  description
  titleTemplate
  twitterUsername
  fbPageUrl
  image {
    __typename
    url
    alt
  }
  _footer
  informations
  networks {
    __typename
    url
    title
    icon
  }
}
