//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  fiches: Fiches;
  fichesConnection: FichesConnection;
  lexique: Lexique;
  lexiqueConnection: LexiqueConnection;
  personnas: Personnas;
  personnasConnection: PersonnasConnection;
  pages: Pages;
  pagesConnection: PagesConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFichesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFichesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FichesFilter>;
};


export type QueryLexiqueArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryLexiqueConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LexiqueFilter>;
};


export type QueryPersonnasArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPersonnasConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PersonnasFilter>;
};


export type QueryPagesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
};

export type DocumentFilter = {
  fiches?: InputMaybe<FichesFilter>;
  lexique?: InputMaybe<LexiqueFilter>;
  personnas?: InputMaybe<PersonnasFilter>;
  pages?: InputMaybe<PagesFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Fiches | Lexique | Personnas | Pages | Folder;

export type FichesValidations = {
  __typename?: 'FichesValidations';
  rule?: Maybe<Scalars['String']['output']>;
  maxValue?: Maybe<Scalars['Float']['output']>;
};

export type Fiches = Node & Document & {
  __typename?: 'Fiches';
  _warning?: Maybe<Scalars['String']['output']>;
  refID: Scalars['String']['output'];
  title: Scalars['String']['output'];
  createdAt?: Maybe<Scalars['String']['output']>;
  updatedAt?: Maybe<Scalars['String']['output']>;
  language: Scalars['String']['output'];
  published: Scalars['Boolean']['output'];
  slug?: Maybe<Scalars['String']['output']>;
  _metadatas?: Maybe<Scalars['String']['output']>;
  people: Scalars['String']['output'];
  scope: Scalars['String']['output'];
  responsible: Array<Scalars['String']['output']>;
  lifecycle: Scalars['String']['output'];
  priority_implementation: Scalars['String']['output'];
  environmental_impact: Scalars['String']['output'];
  saved_resources: Array<Scalars['String']['output']>;
  _corps_de_la_fiche?: Maybe<Scalars['String']['output']>;
  body: Scalars['JSON']['output'];
  validations?: Maybe<Array<Maybe<FichesValidations>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type FichesValidationsFilter = {
  rule?: InputMaybe<StringFilter>;
  maxValue?: InputMaybe<NumberFilter>;
};

export type FichesFilter = {
  _warning?: InputMaybe<StringFilter>;
  refID?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  createdAt?: InputMaybe<DatetimeFilter>;
  updatedAt?: InputMaybe<DatetimeFilter>;
  language?: InputMaybe<StringFilter>;
  published?: InputMaybe<BooleanFilter>;
  slug?: InputMaybe<StringFilter>;
  _metadatas?: InputMaybe<StringFilter>;
  people?: InputMaybe<StringFilter>;
  scope?: InputMaybe<StringFilter>;
  responsible?: InputMaybe<StringFilter>;
  lifecycle?: InputMaybe<StringFilter>;
  priority_implementation?: InputMaybe<StringFilter>;
  environmental_impact?: InputMaybe<StringFilter>;
  saved_resources?: InputMaybe<StringFilter>;
  _corps_de_la_fiche?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
  validations?: InputMaybe<FichesValidationsFilter>;
};

export type FichesConnectionEdges = {
  __typename?: 'FichesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Fiches>;
};

export type FichesConnection = Connection & {
  __typename?: 'FichesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FichesConnectionEdges>>>;
};

export type Lexique = Node & Document & {
  __typename?: 'Lexique';
  _warning?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  createdAt?: Maybe<Scalars['String']['output']>;
  updatedAt?: Maybe<Scalars['String']['output']>;
  language: Scalars['String']['output'];
  published: Scalars['Boolean']['output'];
  slug?: Maybe<Scalars['String']['output']>;
  _corps_de_la_fiche?: Maybe<Scalars['String']['output']>;
  body: Scalars['JSON']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type LexiqueFilter = {
  _warning?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  createdAt?: InputMaybe<DatetimeFilter>;
  updatedAt?: InputMaybe<DatetimeFilter>;
  language?: InputMaybe<StringFilter>;
  published?: InputMaybe<BooleanFilter>;
  slug?: InputMaybe<StringFilter>;
  _corps_de_la_fiche?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type LexiqueConnectionEdges = {
  __typename?: 'LexiqueConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Lexique>;
};

export type LexiqueConnection = Connection & {
  __typename?: 'LexiqueConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<LexiqueConnectionEdges>>>;
};

export type Personnas = Node & Document & {
  __typename?: 'Personnas';
  _warning?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  createdAt?: Maybe<Scalars['String']['output']>;
  updatedAt?: Maybe<Scalars['String']['output']>;
  language: Scalars['String']['output'];
  published: Scalars['Boolean']['output'];
  slug?: Maybe<Scalars['String']['output']>;
  _corps_de_la_fiche?: Maybe<Scalars['String']['output']>;
  body: Scalars['JSON']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PersonnasFilter = {
  _warning?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  createdAt?: InputMaybe<DatetimeFilter>;
  updatedAt?: InputMaybe<DatetimeFilter>;
  language?: InputMaybe<StringFilter>;
  published?: InputMaybe<BooleanFilter>;
  slug?: InputMaybe<StringFilter>;
  _corps_de_la_fiche?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PersonnasConnectionEdges = {
  __typename?: 'PersonnasConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Personnas>;
};

export type PersonnasConnection = Connection & {
  __typename?: 'PersonnasConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PersonnasConnectionEdges>>>;
};

export type Pages = Node & Document & {
  __typename?: 'Pages';
  _warning?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  createdAt?: Maybe<Scalars['String']['output']>;
  updatedAt?: Maybe<Scalars['String']['output']>;
  language: Scalars['String']['output'];
  published: Scalars['Boolean']['output'];
  slug?: Maybe<Scalars['String']['output']>;
  _corps_de_la_fiche?: Maybe<Scalars['String']['output']>;
  useProse?: Maybe<Scalars['Boolean']['output']>;
  body: Scalars['JSON']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PagesFilter = {
  _warning?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  createdAt?: InputMaybe<DatetimeFilter>;
  updatedAt?: InputMaybe<DatetimeFilter>;
  language?: InputMaybe<StringFilter>;
  published?: InputMaybe<BooleanFilter>;
  slug?: InputMaybe<StringFilter>;
  _corps_de_la_fiche?: InputMaybe<StringFilter>;
  useProse?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PagesConnectionEdges = {
  __typename?: 'PagesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pages>;
};

export type PagesConnection = Connection & {
  __typename?: 'PagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PagesConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  updateFiches: Fiches;
  createFiches: Fiches;
  updateLexique: Lexique;
  createLexique: Lexique;
  updatePersonnas: Personnas;
  createPersonnas: Personnas;
  updatePages: Pages;
  createPages: Pages;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationUpdateFichesArgs = {
  relativePath: Scalars['String']['input'];
  params: FichesMutation;
};


export type MutationCreateFichesArgs = {
  relativePath: Scalars['String']['input'];
  params: FichesMutation;
};


export type MutationUpdateLexiqueArgs = {
  relativePath: Scalars['String']['input'];
  params: LexiqueMutation;
};


export type MutationCreateLexiqueArgs = {
  relativePath: Scalars['String']['input'];
  params: LexiqueMutation;
};


export type MutationUpdatePersonnasArgs = {
  relativePath: Scalars['String']['input'];
  params: PersonnasMutation;
};


export type MutationCreatePersonnasArgs = {
  relativePath: Scalars['String']['input'];
  params: PersonnasMutation;
};


export type MutationUpdatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationCreatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};

export type DocumentUpdateMutation = {
  fiches?: InputMaybe<FichesMutation>;
  lexique?: InputMaybe<LexiqueMutation>;
  personnas?: InputMaybe<PersonnasMutation>;
  pages?: InputMaybe<PagesMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  fiches?: InputMaybe<FichesMutation>;
  lexique?: InputMaybe<LexiqueMutation>;
  personnas?: InputMaybe<PersonnasMutation>;
  pages?: InputMaybe<PagesMutation>;
};

export type FichesValidationsMutation = {
  rule?: InputMaybe<Scalars['String']['input']>;
  maxValue?: InputMaybe<Scalars['Float']['input']>;
};

export type FichesMutation = {
  _warning?: InputMaybe<Scalars['String']['input']>;
  refID?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  createdAt?: InputMaybe<Scalars['String']['input']>;
  updatedAt?: InputMaybe<Scalars['String']['input']>;
  language?: InputMaybe<Scalars['String']['input']>;
  published?: InputMaybe<Scalars['Boolean']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  _metadatas?: InputMaybe<Scalars['String']['input']>;
  people?: InputMaybe<Scalars['String']['input']>;
  scope?: InputMaybe<Scalars['String']['input']>;
  responsible?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  lifecycle?: InputMaybe<Scalars['String']['input']>;
  priority_implementation?: InputMaybe<Scalars['String']['input']>;
  environmental_impact?: InputMaybe<Scalars['String']['input']>;
  saved_resources?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  _corps_de_la_fiche?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  validations?: InputMaybe<Array<InputMaybe<FichesValidationsMutation>>>;
};

export type LexiqueMutation = {
  _warning?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  createdAt?: InputMaybe<Scalars['String']['input']>;
  updatedAt?: InputMaybe<Scalars['String']['input']>;
  language?: InputMaybe<Scalars['String']['input']>;
  published?: InputMaybe<Scalars['Boolean']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  _corps_de_la_fiche?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PersonnasMutation = {
  _warning?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  createdAt?: InputMaybe<Scalars['String']['input']>;
  updatedAt?: InputMaybe<Scalars['String']['input']>;
  language?: InputMaybe<Scalars['String']['input']>;
  published?: InputMaybe<Scalars['Boolean']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  _corps_de_la_fiche?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PagesMutation = {
  _warning?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  createdAt?: InputMaybe<Scalars['String']['input']>;
  updatedAt?: InputMaybe<Scalars['String']['input']>;
  language?: InputMaybe<Scalars['String']['input']>;
  published?: InputMaybe<Scalars['Boolean']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  _corps_de_la_fiche?: InputMaybe<Scalars['String']['input']>;
  useProse?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type FichesPartsFragment = { __typename: 'Fiches', _warning?: string | null, refID: string, title: string, createdAt?: string | null, updatedAt?: string | null, language: string, published: boolean, slug?: string | null, _metadatas?: string | null, people: string, scope: string, responsible: Array<string>, lifecycle: string, priority_implementation: string, environmental_impact: string, saved_resources: Array<string>, _corps_de_la_fiche?: string | null, body: any, validations?: Array<{ __typename: 'FichesValidations', rule?: string | null, maxValue?: number | null } | null> | null };

export type LexiquePartsFragment = { __typename: 'Lexique', _warning?: string | null, title: string, createdAt?: string | null, updatedAt?: string | null, language: string, published: boolean, slug?: string | null, _corps_de_la_fiche?: string | null, body: any };

export type PersonnasPartsFragment = { __typename: 'Personnas', _warning?: string | null, title: string, createdAt?: string | null, updatedAt?: string | null, language: string, published: boolean, slug?: string | null, _corps_de_la_fiche?: string | null, body: any };

export type PagesPartsFragment = { __typename: 'Pages', _warning?: string | null, title: string, createdAt?: string | null, updatedAt?: string | null, language: string, published: boolean, slug?: string | null, _corps_de_la_fiche?: string | null, useProse?: boolean | null, body: any };

export type FichesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FichesQuery = { __typename?: 'Query', fiches: { __typename: 'Fiches', id: string, _warning?: string | null, refID: string, title: string, createdAt?: string | null, updatedAt?: string | null, language: string, published: boolean, slug?: string | null, _metadatas?: string | null, people: string, scope: string, responsible: Array<string>, lifecycle: string, priority_implementation: string, environmental_impact: string, saved_resources: Array<string>, _corps_de_la_fiche?: string | null, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, validations?: Array<{ __typename: 'FichesValidations', rule?: string | null, maxValue?: number | null } | null> | null } };

export type FichesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FichesFilter>;
}>;


export type FichesConnectionQuery = { __typename?: 'Query', fichesConnection: { __typename?: 'FichesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FichesConnectionEdges', cursor: string, node?: { __typename: 'Fiches', id: string, _warning?: string | null, refID: string, title: string, createdAt?: string | null, updatedAt?: string | null, language: string, published: boolean, slug?: string | null, _metadatas?: string | null, people: string, scope: string, responsible: Array<string>, lifecycle: string, priority_implementation: string, environmental_impact: string, saved_resources: Array<string>, _corps_de_la_fiche?: string | null, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, validations?: Array<{ __typename: 'FichesValidations', rule?: string | null, maxValue?: number | null } | null> | null } | null } | null> | null } };

export type LexiqueQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type LexiqueQuery = { __typename?: 'Query', lexique: { __typename: 'Lexique', id: string, _warning?: string | null, title: string, createdAt?: string | null, updatedAt?: string | null, language: string, published: boolean, slug?: string | null, _corps_de_la_fiche?: string | null, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type LexiqueConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LexiqueFilter>;
}>;


export type LexiqueConnectionQuery = { __typename?: 'Query', lexiqueConnection: { __typename?: 'LexiqueConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'LexiqueConnectionEdges', cursor: string, node?: { __typename: 'Lexique', id: string, _warning?: string | null, title: string, createdAt?: string | null, updatedAt?: string | null, language: string, published: boolean, slug?: string | null, _corps_de_la_fiche?: string | null, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PersonnasQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PersonnasQuery = { __typename?: 'Query', personnas: { __typename: 'Personnas', id: string, _warning?: string | null, title: string, createdAt?: string | null, updatedAt?: string | null, language: string, published: boolean, slug?: string | null, _corps_de_la_fiche?: string | null, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PersonnasConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PersonnasFilter>;
}>;


export type PersonnasConnectionQuery = { __typename?: 'Query', personnasConnection: { __typename?: 'PersonnasConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PersonnasConnectionEdges', cursor: string, node?: { __typename: 'Personnas', id: string, _warning?: string | null, title: string, createdAt?: string | null, updatedAt?: string | null, language: string, published: boolean, slug?: string | null, _corps_de_la_fiche?: string | null, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PagesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PagesQuery = { __typename?: 'Query', pages: { __typename: 'Pages', id: string, _warning?: string | null, title: string, createdAt?: string | null, updatedAt?: string | null, language: string, published: boolean, slug?: string | null, _corps_de_la_fiche?: string | null, useProse?: boolean | null, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PagesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
}>;


export type PagesConnectionQuery = { __typename?: 'Query', pagesConnection: { __typename?: 'PagesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PagesConnectionEdges', cursor: string, node?: { __typename: 'Pages', id: string, _warning?: string | null, title: string, createdAt?: string | null, updatedAt?: string | null, language: string, published: boolean, slug?: string | null, _corps_de_la_fiche?: string | null, useProse?: boolean | null, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const FichesPartsFragmentDoc = gql`
    fragment FichesParts on Fiches {
  __typename
  _warning
  refID
  title
  createdAt
  updatedAt
  language
  published
  slug
  _metadatas
  people
  scope
  responsible
  lifecycle
  priority_implementation
  environmental_impact
  saved_resources
  _corps_de_la_fiche
  body
  validations {
    __typename
    rule
    maxValue
  }
}
    `;
export const LexiquePartsFragmentDoc = gql`
    fragment LexiqueParts on Lexique {
  __typename
  _warning
  title
  createdAt
  updatedAt
  language
  published
  slug
  _corps_de_la_fiche
  body
}
    `;
export const PersonnasPartsFragmentDoc = gql`
    fragment PersonnasParts on Personnas {
  __typename
  _warning
  title
  createdAt
  updatedAt
  language
  published
  slug
  _corps_de_la_fiche
  body
}
    `;
export const PagesPartsFragmentDoc = gql`
    fragment PagesParts on Pages {
  __typename
  _warning
  title
  createdAt
  updatedAt
  language
  published
  slug
  _corps_de_la_fiche
  useProse
  body
}
    `;
export const FichesDocument = gql`
    query fiches($relativePath: String!) {
  fiches(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FichesParts
  }
}
    ${FichesPartsFragmentDoc}`;
export const FichesConnectionDocument = gql`
    query fichesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FichesFilter) {
  fichesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FichesParts
      }
    }
  }
}
    ${FichesPartsFragmentDoc}`;
export const LexiqueDocument = gql`
    query lexique($relativePath: String!) {
  lexique(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...LexiqueParts
  }
}
    ${LexiquePartsFragmentDoc}`;
export const LexiqueConnectionDocument = gql`
    query lexiqueConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: LexiqueFilter) {
  lexiqueConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...LexiqueParts
      }
    }
  }
}
    ${LexiquePartsFragmentDoc}`;
export const PersonnasDocument = gql`
    query personnas($relativePath: String!) {
  personnas(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PersonnasParts
  }
}
    ${PersonnasPartsFragmentDoc}`;
export const PersonnasConnectionDocument = gql`
    query personnasConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PersonnasFilter) {
  personnasConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PersonnasParts
      }
    }
  }
}
    ${PersonnasPartsFragmentDoc}`;
export const PagesDocument = gql`
    query pages($relativePath: String!) {
  pages(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PagesParts
  }
}
    ${PagesPartsFragmentDoc}`;
export const PagesConnectionDocument = gql`
    query pagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PagesFilter) {
  pagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PagesParts
      }
    }
  }
}
    ${PagesPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      fiches(variables: FichesQueryVariables, options?: C): Promise<{data: FichesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FichesQueryVariables, query: string}> {
        return requester<{data: FichesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FichesQueryVariables, query: string}, FichesQueryVariables>(FichesDocument, variables, options);
      },
    fichesConnection(variables?: FichesConnectionQueryVariables, options?: C): Promise<{data: FichesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FichesConnectionQueryVariables, query: string}> {
        return requester<{data: FichesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FichesConnectionQueryVariables, query: string}, FichesConnectionQueryVariables>(FichesConnectionDocument, variables, options);
      },
    lexique(variables: LexiqueQueryVariables, options?: C): Promise<{data: LexiqueQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LexiqueQueryVariables, query: string}> {
        return requester<{data: LexiqueQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LexiqueQueryVariables, query: string}, LexiqueQueryVariables>(LexiqueDocument, variables, options);
      },
    lexiqueConnection(variables?: LexiqueConnectionQueryVariables, options?: C): Promise<{data: LexiqueConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LexiqueConnectionQueryVariables, query: string}> {
        return requester<{data: LexiqueConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LexiqueConnectionQueryVariables, query: string}, LexiqueConnectionQueryVariables>(LexiqueConnectionDocument, variables, options);
      },
    personnas(variables: PersonnasQueryVariables, options?: C): Promise<{data: PersonnasQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PersonnasQueryVariables, query: string}> {
        return requester<{data: PersonnasQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PersonnasQueryVariables, query: string}, PersonnasQueryVariables>(PersonnasDocument, variables, options);
      },
    personnasConnection(variables?: PersonnasConnectionQueryVariables, options?: C): Promise<{data: PersonnasConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PersonnasConnectionQueryVariables, query: string}> {
        return requester<{data: PersonnasConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PersonnasConnectionQueryVariables, query: string}, PersonnasConnectionQueryVariables>(PersonnasConnectionDocument, variables, options);
      },
    pages(variables: PagesQueryVariables, options?: C): Promise<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}> {
        return requester<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}, PagesQueryVariables>(PagesDocument, variables, options);
      },
    pagesConnection(variables?: PagesConnectionQueryVariables, options?: C): Promise<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}> {
        return requester<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}, PagesConnectionQueryVariables>(PagesConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
  options?: { branch?: string }
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: { branch?: string },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    })

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
  options?: {
    branch?: string
  }
) => {
  const requester = generateRequester(client, options)
  return getSdk(requester)
}

  